### Register a new user
POST http://localhost:8080/user/userreg
Content-Type: application/json

{
  "username": "user22",
  "password": "1234"
}

### Login request
POST http://localhost:8080/user/login
Content-Type: application/x-www-form-urlencoded

username=user22&password=1234

### userList request
GET http://localhost:8080/user/userList
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMjIiLCJpYXQiOjE3MjI0Mzk5NjYsImV4cCI6MTcyMjQ0NzE2Nn0.SeuWtt-665j8A1I3AzGe4H0JDqLp-cwlaXpPF7pzekY
